### ISSUE TITLE
车辆模型的问题

### ISSUE THREAD

**Issue by mengchaoheng** [jhan15/dubins_path_planning#1]
请问车辆模型的速度项是哪一个变量？貌似m或者ml已经用来表示前进、后退了，那simplified car model的速度是在哪里设置？
![image](https://user-images.githubusercontent.com/43166007/174926767-f5795a89-edd5-44d8-8ad7-b35b24d8874c.png)

**Comment by mengchaoheng** [comment]
这里默认是前进，那对于dubin's car 的车辆速度是哪个变量？
<img width="397" alt="image" src="https://user-images.githubusercontent.com/43166007/174926948-1cc33e56-91d7-4313-b522-0fb11e338663.png">

**Comment by mengchaoheng** [comment]
@jhan15

**Comment by jhan15** [comment]
You can assume a velocity of 1 in my case and add a new velocity variable per your needs

**Comment by mengchaoheng** [comment]
> You can assume a velocity of 1 in my case and add a new velocity variable per your needs

Thank you and forgive me for using Chinese, I thought you were Chinese. @jhan15

**Comment by jhan15** [comment]
> > You can assume a velocity of 1 in my case and add a new velocity variable per your needs
> 
> Thank you and forgive me for using Chinese, I thought you were Chinese. @jhan15

I'm Chinese, I was writing in English for better knowledge sharing in case someone has the same issue.

**Comment by mengchaoheng** [comment]
> > > You can assume a velocity of 1 in my case and add a new velocity variable per your needs
> > 
> > 
> > Thank you and forgive me for using Chinese, I thought you were Chinese. @jhan15
> 
> I'm Chinese, I was writing in English for better knowledge sharing in case someone has the same issue.

Thanks! 
In fact, dt is equivalent to the motion resolution, that is, the distance traveled by the vehicle per control cycle. I have forked and updated to my repository.
